### ISSUE TITLE
Generate rdf:ID that complies with standard URI string format

### ISSUE THREAD

**Issue by johardi** [protegeproject/mapping-master#1]
Linked to https://github.com/protegeproject/cellfie-plugin/issues/46

**Comment by martinjoconnor** [comment]
I am hoping that this is purely an IRI validity check which will throw an exception if the IRI the user tries to create is invalid (hopefully with a helpful error message). The OWLAPI should have an appropriate call (thought I am not sure it will have user friendly error messages).

I dot not think that we should attempt to remap any invalid characters.

**Comment by johardi** [comment]
I think the build IRI function is meant for creating IRI string from free labels in the spreadsheet, like `Back To Nature, Fudge Mint Cookies`, `Barbara's Puffins Honey Rice Cereal - 10.5 oz box`, `Mallomars Cookies (Pure Chocolate) - 8 oz tray`. Note the spaces and all writing symbols.

The solution was too simple that I implemented camelCasing strategy for preparing the local name, i.e., remove all whitespaces and the non-alphanumeric characters, and then append the base prefix. Perhaps we should prepare the local name based on the URI syntax rules.

**Comment by martinjoconnor** [comment]
I am wondering if automatic conversion is the way to go. 

Let's assume we have @A1="Fudge Mint Cookies".

If the user types:

`Class: @A1(rdf:ID)`

I am not convinced we should generate a corrected IRI automatically. I think we should throw an intelligent error here.

Instead I would suggest an explicit conversion function, say `iriEncode`.

Then we would have:

`Class: @A1(rdf:ID=mm:iriEncode)`

**Comment by martinjoconnor** [comment]
Perhaps also implement mm:uuid and mm:hash

**Comment by johardi** [comment]
Close https://github.com/protegeproject/mapping-master/issues/1 via  https://github.com/protegeproject/mapping-master/commit/75c3988b11fe9a49f0aa2de8faa04d45ec290963
