### ISSUE TITLE
Error when assigning language tag using `xml:lang` directive

### ISSUE THREAD

**Issue by johardi** [protegeproject/mapping-master#2]
Linked to https://github.com/protegeproject/cellfie-plugin/issues/41

**Comment by martinjoconnor** [comment]
I think if the user supplies an xml:lang directive in a reference we can default the type to rdf:PlainLiteral. 

That is

`Individual: Fred Facts: hasName @A1(xml:lang="en")`

is equivalent to:

`Individual: Fred Facts: hasName @A1(rdf:PlainLiteral xml:lang="en")`

However, if they add another type explicitly then an error should be thrown.

`Individual: Fred Facts: hasName @A1(xsd:string xml:lang="en")`

should generate an exception.

**Comment by johardi** [comment]
Close https://github.com/protegeproject/mapping-master/issues/2 via https://github.com/protegeproject/mapping-master/commit/aaabfe65c83cc9c1ef59834cb09a068a7630225f
