### ISSUE TITLE
Could not load tab in Protege on Mac

### ISSUE THREAD

**Issue by imane0897** [protegeproject/mapping-master#22]
Hi, I'm new to Java. I followed the README file but could not find Mapping Master tab in Protege on my Mac.
### What I did
1. Download the .zip source file, unzip it, cd to the dir and then `mvn clean install`
2. I got a target folder and a mapping-master-1.6.jar
3. I put the .jar file at /Applications/Protege/plugins/ 
4. Restart Protege but find no mapping master tab at Protege/Window/Tabs
### What I tried
I change the dir in step 4 as  /Applications/Protege/Java/plugins and then restart Protege but still not work.
### Environment I use
Protege 5.2.0
macOS Mojave 10.14
### More information
I looked into Protege/About/Installed Plugins and Mapping Master can be seen there.

**Comment by csnyulas** [comment]
MappingMaster is a plug-in written for Protege 3.x.

In Protege 4.x and 5.x there is a different plug-in, called [Cellfie](https://github.com/protegeproject/cellfie-plugin), which uses the MappingMaster DSL to define mappings to import data from spreadsheets. The Cellfie plug-in comes bundled with Protege 5.2 (and many of the earlier versions as well), and can be activated through the `Tools -> Create axioms from Excel workbook...` menu.
