### ISSUE TITLE
Parsing ObjectProperty as an expression

### ISSUE THREAD

**Issue by neobernad** [protegeproject/mapping-master#26]
Hi,

First of all, this issue is related to this one https://github.com/protegeproject/cellfie-plugin/issues/150.

I would like to parse `ObjectProperty:` expressions as I need to annotate relationships in my use cases. I am running the following code to test the functionality:

```java
@Test
@Category(ClassExpressionTest.class)
public void TestAnnotations() throws Exception
{
    setPrefix(ontology, "rdfs", "http://www.w3.org/2000/01/rdf-schema#");
    declareOWLAnnotationProperty(ontology, "rdfs:label");
    declareOWLClasses(ontology, "Person", "Human");
    declareOWLObjectProperties(ontology, "hasParent");
    String expression = "ObjectProperty: hasParent Annotations: rdfs:label 'mylabel'";
    SimpleCharStream jj_input_stream = new SimpleCharStream(new ByteArrayInputStream(expression.getBytes()), "UTF-8", 1, 1);
    MappingMasterParserTokenManager token_source = new MappingMasterParserTokenManager(jj_input_stream);
    assertThat(token_source.getNextToken().kind, is(77));
 }
```
The problem is that the `MappingMasterParserTokenManager` detects the token `ObjectProperty:` as an `IDENTIFIER` since the `token_source.getNextToken().kind` returns `139`, instead of `77` (`OWL_OBJECT_PROPERTY`).

Having a look into the code, the variable `jjmatchedKind` is properly set to `77` kind in the method `jjStartNfaWithStates_0()`, however it is later on is modified in `jjMoveNfa_0()` when running the following `case 261`:

```java
case 261:
   if ((0x7ffe40800000000L & l) != 0L)
   {
      if (kind > 147)
         kind = 147;
      { jjCheckNAdd(22); }
   }
   if ((0x7ffe00800000000L & l) != 0L)
   {
      if (kind > 139)
         kind = 139;
      { jjCheckNAdd(13); }
   }
   break;
```
Where `kind` is rewritten to 139. Is this right? If not could you please let me know how the conditional mask logic works so that I can fix it by myself?

PD: I do not know if this code was autogenerated by another software.

Thanks,
José Antonio

**Comment by martinjoconnor** [comment]
This is code auto-generated by JJTree/JavaCC. 

If you want to add new clauses to the Mapping Master DSL you will first need to extend the grammar by modifying the following file:

https://github.com/protegeproject/mapping-master/blob/master/src/main/jjtree/MappingMasterParser.jjt

You will then need to add code to process the new nodes generated from this grammar.

**Comment by neobernad** [comment]
Thanks Martin for your reply.

According to the method naming I was assuming it was auto-generated, but I did not heard of JavaCC before. I will then have a look to the JavaCC and the grammar file.

Thanks again,
José Antonio
